Code/QL_DCAN/SHOP_DCAN/SHOP_DCAN/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOP_DCAN.Models;
namespace SHOP_DCAN.Controllers
{
    public class KhachHangController : Controller
    {
        // GET: KhachHang
        QL_DCAN2Entities db = new QL_DCAN2Entities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Edit()
        {
            KhachHang customer = Session["KH"] as KhachHang;
            int customerId = customer.MaKH;
           
            if (customer == null)
            {
                return HttpNotFound();
            }

            var model = new EditKhachHang
            {
                MaKH = customer.MaKH,
                TenKH = customer.TenKH,
                SDT = customer.SDT
                // Thêm các thuộc tính khác nếu cần
            };
            return View(model);
        }

        // POST: Customer/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditKhachHang model)
        {
            if (ModelState.IsValid)
            {
                var customer = db.KhachHangs.Find(model.MaKH);
                if (customer == null)
                {
                    return HttpNotFound();
                }

                customer.TenKH = model.TenKH;
                customer.SDT = model.SDT;
                // Cập nhật các thuộc tính khác nếu cần

                db.SaveChanges();
                Session["KH"] = customer;
                return RedirectToAction("LichSuDonHang","Product");
            }

            return View(model);
        }

    }
}

Code/QL_DCAN/SHOP_DCAN/SHOP_DCAN/Views/KhachHang/Edit.cshtml
@model SHOP_DCAN.Models.EditKhachHang
@using (Html.BeginForm("Edit", "KhachHang", FormMethod.Post))
{
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.MaKH)

        <div class="form-group">
        @Html.LabelFor(model => model.TenKH,"Tên Khách Hàng")
        @Html.TextBoxFor(model => model.TenKH, new { @class = "form-control" })
        </div>

        <div class="form-group">
        @Html.LabelFor(model => model.SDT, "Số điện thoại")
        @Html.TextBoxFor(model => model.SDT, new { @class = "form-control" })
        </div>

            <button type="submit" class="btn btn-primary">Save</button>
            }